
void manzhuk(//Решатель ДАУ на полных матрицах
    double z[],
    double px[],
    double z1[],
    double px1[],
    double f[],
    double rj1[],
    double rj2[],
    double t,
    double t0,
    double tk,
    double h,
    double hmn,
    double hmx,
    double eps,
    double *tkv,
    int n,
    int m,
    int nm,
    int ncon,
    int *nbad,
    int *ier,
    int ip[],
    void fct(double z[],double px[],double f[],double rj1[],double rj2[],
                int n,int m,double t,double h, int ncon,int *nbad,int ip[]),
    void out(double z[],double xp[],int n,int m,double t,double t0,double tk,
                double h,double *tkv,int ncon,int ip[])
);
